# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0acb98dbddc7cd965f635f44db9e2b8b08d4e27e581459656e2930c82d60092f9e8c2ba6cf70c41e6766df00c4c660242235b92770096fbb8bfb5f501dbc402

test:
  secret_key_base: 4205114ec1050cfa46dd80f03d8ba9daf419c5b3b4b3e97305afe50b7c1bf4fc9627dbf54ec38f5b467afa5babea4013e485bb09e7a1dcb371526270c377099c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
